image: androidsdk/android-30

clone:
  depth: full
pipelines:
  branches:
    master:
      - step:
          script:
            - git push --mirror git@github.com:BaturaMobile/ZeroBaturaLibrary.git
      - step:
          name: Android Debug Application
          caches:
            - gradle
          script:
            - ./gradlew assembleDebug
          artifacts:
            - app/build/outputs/**